ci: add notify release workflow
okp4/faucet-web pull request #100
Opened 2022-09-12 18:29 UTC by warstrolo

Add the notify release workflow for faucet web repo

2022-09-12 19:05 UTC, fredericvilcot requested changes

2022-09-12 19:05 UTC, fredericvilcot commented on .github/workflows/notify-release.yml
> +              "content": " 🚨 A new version of @${{ github.repository }} ${{ github.event.release.tag_name }} has been released! 🎉\n\n👉 Changelog: https://github.com/${{ github.repository }}/releases/
```suggestion
              "content": "🚨 A new version of @${{ github.repository }} ${{ github.event.release.tag_name }} has been released! 🎉\n\n👉 Changelog: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}\n 👉 Official repo: https://github.com/${{ github.repository }}"
```

Seems useless here 😌

2022-09-13 06:08 UTC, amimart requested changes

2022-09-13 06:08 UTC, amimart commented on .github/workflows/notify-release.yml
> +              "content": " 🚨 A new version of @${{ github.repository }} ${{ github.event.release.tag_name }} has been released! 🎉\n\n👉 Changelog: https://github.com/${{ github.repository }}/releases/
```suggestion
              "content": "🚨 A new version of @${{ github.repository }} ${{ github.event.release.tag_name }} has been released! 🎉\n\n👉 Changelog: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}\n👉 Official repo: https://github.com/${{ github.repository }}"
```

2022-09-13 07:43 UTC, amimart approved these changes

2022-09-13 08:24 UTC, fredericvilcot approved these changes

2022-09-13 08:35 UTC, merged